### ISSUE TITLE
TaoBaoSpider.java

### ISSUE THREAD

**Issue by 77266989** [MartinDai/TBSpider#4]
TaoBaoSpider.java里的main方法为什么执行第一次可以返回数据，第二次就返回null了。是不是淘宝的反扒机制？

**Comment by MartinDai** [comment]
> TaoBaoSpider.java里的main方法为什么执行第一次可以返回数据，第二次就返回null了。是不是淘宝的反扒机制？

我这边没有返回null，你可以debug看看是不是哪里报错了
